[package]
name = "UpdateVpnList"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.22"
tokio = { version = "1", features = ["full"] }
futures = "0.3.31"
serde_yaml = "0.9.33"
serde = { version = "1.0.219", features = ["derive"] }
async-std = "1.13.1"
device_query = "4.0.1"